### PR TITLE
chore: upgrade base image

### PR DESCRIPTION
**Pull request by dicolasi**

### CODE REVIEW

**Comment by rawlingsj** [comment]
CI failure:
```
INFO[0019] Running: [/bin/sh -c mkdir -p /usr/share/maven /usr/share/maven/ref   && echo "Downlaoding maven"   && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz     && echo "Checking download hash"   && echo "${SHA}  /tmp/apache-maven.tar.gz" \| sha512sum -c -     && echo "Unziping maven"   && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1     && echo "Cleaning and setting links"   && rm -f /tmp/apache-maven.tar.gz   && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn]
--
  |   |   |   | Downlaoding maven
  |   |   |   | curl: (22) The requested URL returned error: 404 Not Found
  |   |   |   | error building image: error building stage: failed to execute command: waiting for process to exit: exit status 22
```

**Comment by dicolasi** [comment]
@rawlingsj  don't get it really. Is there a connection problem for downloading maven?

**Pull request merged**
